### ISSUE TITLE
How do I add stats to my readme?

### ISSUE THREAD

**Issue by ae00n** [gautamkrishnar/gautamkrishnar#3]
Hey, could someone help me on how to add the kind of stats gautamkrishnar has in my README.md?

**Comment by gautamkrishnar** [comment]
Hello @yungbeatz sorry for the late reply, please use https://github.com/anuraghazra/github-readme-stats

https://github.com/anuraghazra/github-readme-stats#wakatime-week-stats to be specific

**Comment by ae00n** [comment]
Thanks so much @gautamkrishnar!
As soon as I have time, I will try to add it to my README! 
Is it ok if I created another issue if I get any problems, or should I talk to the WakaTime support?

**Comment by gautamkrishnar** [comment]
Please create an issue at https://github.com/anuraghazra/issues if you are facing problems. Yes you can also contact wakatime support if it is not working.
