### ISSUE TITLE
Broken Stackoverflow view

### ISSUE THREAD

**Issue by saigkill** [gautamkrishnar/gautamkrishnar#4]
I'm using [that](https://github.com/saigkill/saigkill/blob/master/.github/workflows/stack-overflow-workflow.yml) workflow with Stackoverflow.
As you can see on my [profile page](https://github.com/saigkill/saigkill) the output looks a little bit broken. Maybe i have missed anything?

**Comment by gautamkrishnar** [comment]
@saigkill please open an issue at https://github.com/anuraghazra/github-readme-stats and let them know the issue, I am not a maintainer of that project.
